group: others
depends_on:
  - forge
steps:
  # dependencies
  - label: ":tapioca: build: pip-compile dependencies"
    key: pip_compile_dependencies
    instance_type: small
    commands:
      # uncomment the following line to update the pinned versions of pip dependencies
      # to the latest versions; otherwise, the pinned versions will be re-used as much
      # as possible
      # - rm ./python/requirements_compiled.txt
      - cp ./python/requirements_compiled_rayllm_py311_cpu.txt requirements_compiled_rayllm_py311_cpu_backup.txt
      - cp ./python/requirements_compiled_rayllm_py311_cu121.txt requirements_compiled_rayllm_py311_cu121_backup.txt
      - cp ./python/requirements_compiled_rayllm_py311_cu124.txt requirements_compiled_rayllm_py311_cu124_backup.txt
      - ./ci/ci.sh compile_llm_requirements
      - cp -f ./python/requirements_compiled_rayllm_py311_cpu.txt /artifact-mount/
      - cp -f ./python/requirements_compiled_rayllm_py311_cu121.txt /artifact-mount/
      - cp -f ./python/requirements_compiled_rayllm_py311_cu124.txt /artifact-mount/
      - |
        FAILED=0
        diff ./python/requirements_compiled_rayllm_py311_cpu.txt requirements_compiled_rayllm_py311_cpu_backup.txt || {
          echo "requirements_compiled_rayllm_py311_cpu.txt is not up to date. Please download it from Artifacts tab and git push the changes."
          FAILED=1
        }
        diff ./python/requirements_compiled_rayllm_py311_cu121.txt requirements_compiled_rayllm_py311_cu121_backup.txt || {
          echo "requirements_compiled_rayllm_py311_cu121.txt is not up to date. Please download it from Artifacts tab and git push the changes."
          FAILED=1
        }
        diff ./python/requirements_compiled_rayllm_py311_cu124.txt requirements_compiled_rayllm_py311_cu124_backup.txt || {
          echo "requirements_compiled_rayllm_py311_cu124.txt is not up to date. Please download it from Artifacts tab and git push the changes."
          FAILED=1
        }
        if [ $FAILED -eq 1 ]; then
          exit 1
        fi
    soft_fail: true
    job_env: oss-ci-base_test-py3.11
    depends_on: oss-ci-base_test-multipy

  - label: ":tapioca: build: uv pip compile LLM dependencies"
    key: uv_pip_compile_llm_dependencies
    instance_type: small
    commands:
      # uncomment the following line to update the pinned versions of pip dependencies
      # to the latest versions; otherwise, the pinned versions will be re-used as much
      # as possible
      # - rm ./python/requirements_compiled.txt
      - cp ./python/requirements_compiled.txt requirements_compiled_backup.txt
      - ./ci/ci.sh compile_llm_requirements
      - cp -f ./python/requirements_compiled.txt /artifact-mount/
      - diff ./python/requirements_compiled.txt requirements_compiled_backup.txt || (echo "requirements_compiled.txt is not up to date. Please download it from Artifacts tab and git push the changes." && exit 1)
    soft_fail: true
    job_env: oss-ci-base_test-py3.11
    depends_on: oss-ci-base_test-multipy
  
  # docs
  - name: doctestbuild
    wanda: ci/docker/doctest.build.wanda.yaml
    depends_on: oss-ci-base_build

  - label: doc tests
    instance_type: large
    commands:
      # doc tests
      - bazel run //ci/ray_ci:test_in_docker -- //python/ray/... //doc/... none
        --build-name doctestbuild
        --only-tags doctest
        --except-tags gpu
        --parallelism-per-worker 3
      # doc memory pressure example
      - bazel run //ci/ray_ci:test_in_docker -- //doc/... core
        --build-name doctestbuild
        --only-tags mem_pressure
        --except-tags gpu
        --skip-ray-installation
    depends_on: doctestbuild

  # java
  - label: ":java: java tests"
    tags: java
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:test_in_docker -- //... core --build-only
      - docker run -i --rm --volume /tmp/artifacts:/artifact-mount --shm-size=2.5gb
        "$${RAYCI_WORK_REPO}":"$${RAYCI_BUILD_ID}"-corebuild /bin/bash -iecuo pipefail
        "./java/test.sh"
    depends_on: corebuild

  # bot
  - label: ":robot_face: CI weekly green metric"
    tags:
      - skip-on-premerge
      - oss
    if: build.branch == "master"
    instance_type: small
    commands:
      - bazel run //ci/ray_ci/automation:weekly_green_metric -- --production

  - label: ":robot_face: {{matrix}} microcheck test coverage"
    tags:
      - skip-on-premerge
      - oss
    if: build.branch == "master"
    instance_type: small
    commands:
      - bazel run //ci/ray_ci/automation:determine_microcheck_tests -- {{matrix}} 100 --test-prefix linux:__ --production
      # we use master branch to determine microcheck tests for darwin and windows, because darwin and windows tests do not run on premerge branches
      - bazel run //ci/ray_ci/automation:determine_microcheck_tests -- {{matrix}} 100 --test-prefix darwin:__ --consider-master-branch --production
      - bazel run //ci/ray_ci/automation:determine_microcheck_tests -- {{matrix}} 100 --test-prefix windows:__ --consider-master-branch --production
    matrix:
      - "core"
      - "serverless"
      - "serve"
      - "data"
      - "ml"
      - "rllib"
      - "ci"
