FROM rayproject/ray:2.44.0-py312-cpu

# Install vllm from local wheel to include custom changes
COPY lamini/vllm-0.7.2.post2.dev102+g4365059e.cpu-cp312-cp312-linux_x86_64.whl /tmp/

RUN pip install --no-cache-dir \
    'ray[serve,llm]>=2.44.0' \
    /tmp/vllm-0.7.2.post2.dev102+g4365059e.cpu-cp312-cp312-linux_x86_64.whl \
    pynvml==12.0.0 \
    awscli asyncache httpx

# Define Python path as a variable for easier maintenance
ENV PYTHON_PATH=/home/ray/anaconda3/lib/python3.12/site-packages

# replace `lora_model_loader.py`, support load loRA model from local file
COPY python/ray/llm/_internal/serve/deployments/llm/multiplex/lora_model_loader.py ${PYTHON_PATH}/ray/llm/_internal/serve/deployments/llm/multiplex/lora_model_loader.py

# replace `json_mode_utils.py`, support json_mode unevaluatedProperties True
COPY python/ray/llm/_internal/serve/configs/json_mode_utils.py ${PYTHON_PATH}/ray/llm/_internal/serve/configs/json_mode_utils.py

# replace `vllm_engine.py`, add more logging for vllm engine
COPY python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py ${PYTHON_PATH}/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py

## for MoME integration ##
COPY python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py ${PYTHON_PATH}/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
COPY python/ray/llm/_internal/serve/deployments/llm/llm_server.py ${PYTHON_PATH}/ray/llm/_internal/serve/deployments/llm/llm_server.py
COPY python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py ${PYTHON_PATH}/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
COPY python/ray/llm/_internal/serve/config_generator/generator.py ${PYTHON_PATH}/ray/llm/_internal/serve/config_generator/generator.py
COPY python/ray/llm/_internal/serve/config_generator/inputs.py ${PYTHON_PATH}/ray/llm/_internal/serve/config_generator/inputs.py
COPY python/ray/llm/_internal/serve/config_generator/start.py ${PYTHON_PATH}/ray/llm/_internal/serve/config_generator/start.py
COPY python/ray/llm/_internal/serve/config_generator/utils/input_converter.py ${PYTHON_PATH}/ray/llm/_internal/serve/config_generator/utils/input_converter.py
COPY python/ray/llm/_internal/serve/config_generator/utils/models.py ${PYTHON_PATH}/ray/llm/_internal/serve/config_generator/utils/models.py
COPY python/ray/llm/_internal/serve/configs/server_models.py ${PYTHON_PATH}/ray/llm/_internal/serve/configs/server_models.py
